version: '3.1'

services:
  mysql:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: l4me_p4ssword
      MYSQL_DATABASE: yourls
      MYSQL_USER: biglou
      MYSQL_PASSWORD: l4me_p4ssword
    networks:
      - big-network

  yourls:
    image: yourls
    restart: always
    ports:
      - 80:80
    environment:
      YOURLS_DB_PASS: l4me_p4ssword
      YOURLS_USER: biglou
      YOURLS_PASS: l4me_p4ssword
      YOURLS_DB_HOST: mysql
      YOURLS_DB_USER: root
      YOURLS_DB_NAME: yourls
      YOURLS_SITE: http://docker01-louis.louis.local
    depends_on: 
      - mysql
    networks:
      - big-network      
networks:
  big-network:
    driver: bridge
